# Ruff configuration - replaces Black, isort, and basic linting
line-length = 88
target-version = "py39"

[lint]
select = ["E", "W", "F", "I"]
ignore = ["E501"]  # Line length handled by formatter

[format]
quote-style = "double"
